apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels:
    app: shipping
    purpose: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: shipping
    spec:
      tolerations:
        - key: "purpose"
          operator: "Equal"
          value: "roboshop"
          effect: "PreferNoSchedule"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - shipping
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: shipping
          image: 826334059644.dkr.ecr.us-east-1.amazonaws.com/shipping_demo:latest
          ports:
            - containerPort: 8080
          # it's Java it needs lots of memory
          resources:
            limits:
              cpu: 200m
              memory: 1000Mi
            requests:
              cpu: 100m
              memory: 500Mi
          env:
            - name: CART_ENDPOINT
              value: "cart:8080"
            - name: DB_HOST
              value: mysql #mysql.roboshop.com

